import type { VisualMemory } from "./types";

export function resolveContinuationMemory(
  memories: VisualMemory[],
  sourceImageUrl?: string,
  sceneId?: string,
): VisualMemory | undefined {
  const sourceMatch = sourceImageUrl
    ? memories.find((item) => item.imageUrl === sourceImageUrl)
    : undefined;
  if (sourceMatch) return sourceMatch;
  return sceneId ? memories.find((item) => item.sceneId === sceneId) : undefined;
}

/**
 * A thread-level scene id may only stand in for a missing per-photo scene id
 * when the selected photo was generated by the assistant. User-uploaded images
 * must not inherit unrelated thread context.
 */
export function resolveLastPhotoSceneId(
  photoSceneId?: string,
  photoRole?: string,
  worldSceneId?: string,
): string | undefined {
  if (photoSceneId) return photoSceneId;
  return photoRole === "assistant" ? worldSceneId : undefined;
}


/**
 * Freeze the source photo for a turn at the point that turn's message entered
 * the thread. Async model/generation work must not silently switch to a photo
 * added by a later message.
 */
export function resolveTurnPhotoSnapshot<T extends { id: string; imageUrl?: string }>(
  messages: T[],
  messageId: string,
): T | undefined {
  const messageIndex = messages.findIndex((item) => item.id === messageId);
  if (messageIndex < 0) return undefined;
  const relevant = messages.slice(0, messageIndex + 1);
  return [...relevant].reverse().find((item) => Boolean(item.imageUrl));
}
