import type { VisualMemory } from "./types";

export function resolveContinuationMemory(
  memories: VisualMemory[],
  sourceImageUrl?: string,
  sceneId?: string,
): VisualMemory | undefined {
  const sourceMatch = sourceImageUrl
    ? memories.find((item) => item.imageUrl === sourceImageUrl)
    : undefined;
  if (sourceMatch) return sourceMatch;
  return sceneId ? memories.find((item) => item.sceneId === sceneId) : undefined;
}

/**
 * A thread-level scene id may only stand in for a missing per-photo scene id
 * when the selected photo was generated by the assistant. User-uploaded images
 * must not inherit unrelated thread context.
 */
export function resolveLastPhotoSceneId(
  photoSceneId?: string,
  photoRole?: string,
  worldSceneId?: string,
): string | undefined {
  if (photoSceneId) return photoSceneId;
  return photoRole === "assistant" ? worldSceneId : undefined;
}
