/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DropboxOauthRouteImport } from './routes/dropbox-oauth'
import { Route as ApiAutosaveRouteImport } from './routes/api/autosave'
import { Route as ApiAutosaveConfigRouteImport } from './routes/api/autosave-config'
import { Route as ApiChatDumpRouteImport } from './routes/api/chat-dump'
import { Route as ApiChatMediaRouteImport } from './routes/api/chat-media'
import { Route as ApiDropboxFileRouteImport } from './routes/api/dropbox-file'
import { Route as ApiDropboxUploadRouteImport } from './routes/api/dropbox-upload'
import { Route as ApiGrokChatRouteImport } from './routes/api/grok-chat'
import { Route as ApiGrokOriginRouteImport } from './routes/api/grok-origin'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiLogsRouteImport } from './routes/api/logs'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as ApiRpcRouteImport } from './routes/api/rpc'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ApiStateRouteImport } from './routes/api/state'
import { Route as ApiTickRouteImport } from './routes/api/tick'
import { Route as ApiTokensRouteImport } from './routes/api/tokens'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DropboxOauthRoute = DropboxOauthRouteImport.update({
  id: '/dropbox-oauth',
  path: '/dropbox-oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutosaveRoute = ApiAutosaveRouteImport.update({
  id: '/api/autosave',
  path: '/api/autosave',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutosaveConfigRoute = ApiAutosaveConfigRouteImport.update({
  id: '/api/autosave-config',
  path: '/api/autosave-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatDumpRoute = ApiChatDumpRouteImport.update({
  id: '/api/chat-dump',
  path: '/api/chat-dump',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatMediaRoute = ApiChatMediaRouteImport.update({
  id: '/api/chat-media',
  path: '/api/chat-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDropboxFileRoute = ApiDropboxFileRouteImport.update({
  id: '/api/dropbox-file',
  path: '/api/dropbox-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDropboxUploadRoute = ApiDropboxUploadRouteImport.update({
  id: '/api/dropbox-upload',
  path: '/api/dropbox-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrokChatRoute = ApiGrokChatRouteImport.update({
  id: '/api/grok-chat',
  path: '/api/grok-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrokOriginRoute = ApiGrokOriginRouteImport.update({
  id: '/api/grok-origin',
  path: '/api/grok-origin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogsRoute = ApiLogsRouteImport.update({
  id: '/api/logs',
  path: '/api/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcRoute = ApiRpcRouteImport.update({
  id: '/api/rpc',
  path: '/api/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStateRoute = ApiStateRouteImport.update({
  id: '/api/state',
  path: '/api/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTickRoute = ApiTickRouteImport.update({
  id: '/api/tick',
  path: '/api/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensRoute = ApiTokensRouteImport.update({
  id: '/api/tokens',
  path: '/api/tokens',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dropbox-oauth': typeof DropboxOauthRoute
  '/api/autosave': typeof ApiAutosaveRoute
  '/api/autosave-config': typeof ApiAutosaveConfigRoute
  '/api/chat-dump': typeof ApiChatDumpRoute
  '/api/chat-media': typeof ApiChatMediaRoute
  '/api/dropbox-file': typeof ApiDropboxFileRoute
  '/api/dropbox-upload': typeof ApiDropboxUploadRoute
  '/api/grok-chat': typeof ApiGrokChatRoute
  '/api/grok-origin': typeof ApiGrokOriginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/media': typeof ApiMediaRoute
  '/api/rpc': typeof ApiRpcRoute
  '/api/session': typeof ApiSessionRoute
  '/api/state': typeof ApiStateRoute
  '/api/tick': typeof ApiTickRoute
  '/api/tokens': typeof ApiTokensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dropbox-oauth': typeof DropboxOauthRoute
  '/api/autosave': typeof ApiAutosaveRoute
  '/api/autosave-config': typeof ApiAutosaveConfigRoute
  '/api/chat-dump': typeof ApiChatDumpRoute
  '/api/chat-media': typeof ApiChatMediaRoute
  '/api/dropbox-file': typeof ApiDropboxFileRoute
  '/api/dropbox-upload': typeof ApiDropboxUploadRoute
  '/api/grok-chat': typeof ApiGrokChatRoute
  '/api/grok-origin': typeof ApiGrokOriginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/media': typeof ApiMediaRoute
  '/api/rpc': typeof ApiRpcRoute
  '/api/session': typeof ApiSessionRoute
  '/api/state': typeof ApiStateRoute
  '/api/tick': typeof ApiTickRoute
  '/api/tokens': typeof ApiTokensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dropbox-oauth': typeof DropboxOauthRoute
  '/api/autosave': typeof ApiAutosaveRoute
  '/api/autosave-config': typeof ApiAutosaveConfigRoute
  '/api/chat-dump': typeof ApiChatDumpRoute
  '/api/chat-media': typeof ApiChatMediaRoute
  '/api/dropbox-file': typeof ApiDropboxFileRoute
  '/api/dropbox-upload': typeof ApiDropboxUploadRoute
  '/api/grok-chat': typeof ApiGrokChatRoute
  '/api/grok-origin': typeof ApiGrokOriginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/media': typeof ApiMediaRoute
  '/api/rpc': typeof ApiRpcRoute
  '/api/session': typeof ApiSessionRoute
  '/api/state': typeof ApiStateRoute
  '/api/tick': typeof ApiTickRoute
  '/api/tokens': typeof ApiTokensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dropbox-oauth'
    | '/api/autosave'
    | '/api/autosave-config'
    | '/api/chat-dump'
    | '/api/chat-media'
    | '/api/dropbox-file'
    | '/api/dropbox-upload'
    | '/api/grok-chat'
    | '/api/grok-origin'
    | '/api/health'
    | '/api/logs'
    | '/api/media'
    | '/api/rpc'
    | '/api/session'
    | '/api/state'
    | '/api/tick'
    | '/api/tokens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dropbox-oauth'
    | '/api/autosave'
    | '/api/autosave-config'
    | '/api/chat-dump'
    | '/api/chat-media'
    | '/api/dropbox-file'
    | '/api/dropbox-upload'
    | '/api/grok-chat'
    | '/api/grok-origin'
    | '/api/health'
    | '/api/logs'
    | '/api/media'
    | '/api/rpc'
    | '/api/session'
    | '/api/state'
    | '/api/tick'
    | '/api/tokens'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dropbox-oauth'
    | '/api/autosave'
    | '/api/autosave-config'
    | '/api/chat-dump'
    | '/api/chat-media'
    | '/api/dropbox-file'
    | '/api/dropbox-upload'
    | '/api/grok-chat'
    | '/api/grok-origin'
    | '/api/health'
    | '/api/logs'
    | '/api/media'
    | '/api/rpc'
    | '/api/session'
    | '/api/state'
    | '/api/tick'
    | '/api/tokens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DropboxOauthRoute: typeof DropboxOauthRoute
  ApiAutosaveRoute: typeof ApiAutosaveRoute
  ApiAutosaveConfigRoute: typeof ApiAutosaveConfigRoute
  ApiChatDumpRoute: typeof ApiChatDumpRoute
  ApiChatMediaRoute: typeof ApiChatMediaRoute
  ApiDropboxFileRoute: typeof ApiDropboxFileRoute
  ApiDropboxUploadRoute: typeof ApiDropboxUploadRoute
  ApiGrokChatRoute: typeof ApiGrokChatRoute
  ApiGrokOriginRoute: typeof ApiGrokOriginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLogsRoute: typeof ApiLogsRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ApiRpcRoute: typeof ApiRpcRoute
  ApiSessionRoute: typeof ApiSessionRoute
  ApiStateRoute: typeof ApiStateRoute
  ApiTickRoute: typeof ApiTickRoute
  ApiTokensRoute: typeof ApiTokensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropbox-oauth': {
      id: '/dropbox-oauth'
      path: '/dropbox-oauth'
      fullPath: '/dropbox-oauth'
      preLoaderRoute: typeof DropboxOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autosave': {
      id: '/api/autosave'
      path: '/api/autosave'
      fullPath: '/api/autosave'
      preLoaderRoute: typeof ApiAutosaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autosave-config': {
      id: '/api/autosave-config'
      path: '/api/autosave-config'
      fullPath: '/api/autosave-config'
      preLoaderRoute: typeof ApiAutosaveConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-dump': {
      id: '/api/chat-dump'
      path: '/api/chat-dump'
      fullPath: '/api/chat-dump'
      preLoaderRoute: typeof ApiChatDumpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-media': {
      id: '/api/chat-media'
      path: '/api/chat-media'
      fullPath: '/api/chat-media'
      preLoaderRoute: typeof ApiChatMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dropbox-file': {
      id: '/api/dropbox-file'
      path: '/api/dropbox-file'
      fullPath: '/api/dropbox-file'
      preLoaderRoute: typeof ApiDropboxFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dropbox-upload': {
      id: '/api/dropbox-upload'
      path: '/api/dropbox-upload'
      fullPath: '/api/dropbox-upload'
      preLoaderRoute: typeof ApiDropboxUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grok-chat': {
      id: '/api/grok-chat'
      path: '/api/grok-chat'
      fullPath: '/api/grok-chat'
      preLoaderRoute: typeof ApiGrokChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grok-origin': {
      id: '/api/grok-origin'
      path: '/api/grok-origin'
      fullPath: '/api/grok-origin'
      preLoaderRoute: typeof ApiGrokOriginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logs': {
      id: '/api/logs'
      path: '/api/logs'
      fullPath: '/api/logs'
      preLoaderRoute: typeof ApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc': {
      id: '/api/rpc'
      path: '/api/rpc'
      fullPath: '/api/rpc'
      preLoaderRoute: typeof ApiRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/state': {
      id: '/api/state'
      path: '/api/state'
      fullPath: '/api/state'
      preLoaderRoute: typeof ApiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tick': {
      id: '/api/tick'
      path: '/api/tick'
      fullPath: '/api/tick'
      preLoaderRoute: typeof ApiTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens': {
      id: '/api/tokens'
      path: '/api/tokens'
      fullPath: '/api/tokens'
      preLoaderRoute: typeof ApiTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DropboxOauthRoute: DropboxOauthRoute,
  ApiAutosaveRoute: ApiAutosaveRoute,
  ApiAutosaveConfigRoute: ApiAutosaveConfigRoute,
  ApiChatDumpRoute: ApiChatDumpRoute,
  ApiChatMediaRoute: ApiChatMediaRoute,
  ApiDropboxFileRoute: ApiDropboxFileRoute,
  ApiDropboxUploadRoute: ApiDropboxUploadRoute,
  ApiGrokChatRoute: ApiGrokChatRoute,
  ApiGrokOriginRoute: ApiGrokOriginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLogsRoute: ApiLogsRoute,
  ApiMediaRoute: ApiMediaRoute,
  ApiRpcRoute: ApiRpcRoute,
  ApiSessionRoute: ApiSessionRoute,
  ApiStateRoute: ApiStateRoute,
  ApiTickRoute: ApiTickRoute,
  ApiTokensRoute: ApiTokensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
